### ISSUE TITLE
Panic converting a synthesized basic CDK program

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-aws-native#1304]
### What happened?

I get a panic converting a basic synthesized CDK program:

```bash
$ cf2pulumi nodejs ../cdk/template.yaml
panic: fatal: An assertion has failed

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.91.1/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.91.1/go/common/util/contract/assert.go:28
github.com/pulumi/pulumi-aws-native/provider/pkg/cf2pulumi.(*renderContext).renderResource(0x140030f0eb0, 0x14002a67bf0?)
        /Users/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/cf2pulumi/renderer.go:871 +0x11d4
github.com/pulumi/pulumi-aws-native/provider/pkg/cf2pulumi.RenderTemplate(0x16b9a2e09?, 0x140032ba2e8)
        /Users/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/cf2pulumi/renderer.go:1296 +0x1138
github.com/pulumi/pulumi-aws-native/provider/pkg/cf2pulumi.RenderFile({0x16b9a2e09, 0x14}, 0x70c83?)
        /Users/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/cf2pulumi/renderer.go:1317 +0xc4
main.main()
        /Users/runner/work/pulumi-aws-native/pulumi-aws-native/provider/cmd/cf2pulumi/main.go:46 +0x1e4
```

### Example

Here's my CDK source:

```typescript
import * as cdk from 'aws-cdk-lib';
import { Vpc } from 'aws-cdk-lib/aws-ec2';
import { Construct } from 'constructs';

export class CdkStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new Vpc(this, "convert-cfn", {
      natGateways: 1,
      restrictDefaultSecurityGroup: false
    });
  }
}
```

Here's the synthesized YAML. Note that I commented out the `CDKMetadata` resource due to this error:

```bash
$ cf2pulumi nodejs ../cdk/template.yaml
2024/01/31 15:45:46 failed to render template: unsupported property 'Condition' in resource 'CDKMetadata'
```

```yaml
Resources:
  convertcfn1E0C967A:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: CdkStack/convert-cfn
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/Resource
  convertcfnPublicSubnet1Subnet340EBE50:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.0.0/18
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Public
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: CdkStack/convert-cfn/PublicSubnet1
      VpcId:
        Ref: convertcfn1E0C967A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet1/Subnet
  convertcfnPublicSubnet1RouteTableB8034E6B:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: CdkStack/convert-cfn/PublicSubnet1
      VpcId:
        Ref: convertcfn1E0C967A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet1/RouteTable
  convertcfnPublicSubnet1RouteTableAssociation08443089:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: convertcfnPublicSubnet1RouteTableB8034E6B
      SubnetId:
        Ref: convertcfnPublicSubnet1Subnet340EBE50
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet1/RouteTableAssociation
  convertcfnPublicSubnet1DefaultRouteDCF3FC8A:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: convertcfnIGWCBCB9568
      RouteTableId:
        Ref: convertcfnPublicSubnet1RouteTableB8034E6B
    DependsOn:
      - convertcfnVPCGWBD5A227E
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet1/DefaultRoute
  convertcfnPublicSubnet1EIP87320EE5:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: CdkStack/convert-cfn/PublicSubnet1
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet1/EIP
  convertcfnPublicSubnet1NATGateway2E278E89:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - convertcfnPublicSubnet1EIP87320EE5
          - AllocationId
      SubnetId:
        Ref: convertcfnPublicSubnet1Subnet340EBE50
      Tags:
        - Key: Name
          Value: CdkStack/convert-cfn/PublicSubnet1
    DependsOn:
      - convertcfnPublicSubnet1DefaultRouteDCF3FC8A
      - convertcfnPublicSubnet1RouteTableAssociation08443089
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet1/NATGateway
  convertcfnPublicSubnet2Subnet76F4E4C5:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.64.0/18
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Public
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: CdkStack/convert-cfn/PublicSubnet2
      VpcId:
        Ref: convertcfn1E0C967A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet2/Subnet
  convertcfnPublicSubnet2RouteTable432F5ACD:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: CdkStack/convert-cfn/PublicSubnet2
      VpcId:
        Ref: convertcfn1E0C967A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet2/RouteTable
  convertcfnPublicSubnet2RouteTableAssociation708AED31:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: convertcfnPublicSubnet2RouteTable432F5ACD
      SubnetId:
        Ref: convertcfnPublicSubnet2Subnet76F4E4C5
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet2/RouteTableAssociation
  convertcfnPublicSubnet2DefaultRouteD7988B85:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: convertcfnIGWCBCB9568
      RouteTableId:
        Ref: convertcfnPublicSubnet2RouteTable432F5ACD
    DependsOn:
      - convertcfnVPCGWBD5A227E
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PublicSubnet2/DefaultRoute
  convertcfnPrivateSubnet1SubnetFD664330:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.128.0/18
      MapPublicIpOnLaunch: false
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Private
        - Key: aws-cdk:subnet-type
          Value: Private
        - Key: Name
          Value: CdkStack/convert-cfn/PrivateSubnet1
      VpcId:
        Ref: convertcfn1E0C967A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PrivateSubnet1/Subnet
  convertcfnPrivateSubnet1RouteTable5ED95E6A:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: CdkStack/convert-cfn/PrivateSubnet1
      VpcId:
        Ref: convertcfn1E0C967A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PrivateSubnet1/RouteTable
  convertcfnPrivateSubnet1RouteTableAssociation8480EA54:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: convertcfnPrivateSubnet1RouteTable5ED95E6A
      SubnetId:
        Ref: convertcfnPrivateSubnet1SubnetFD664330
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PrivateSubnet1/RouteTableAssociation
  convertcfnPrivateSubnet1DefaultRouteE6E5453E:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: convertcfnPublicSubnet1NATGateway2E278E89
      RouteTableId:
        Ref: convertcfnPrivateSubnet1RouteTable5ED95E6A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PrivateSubnet1/DefaultRoute
  convertcfnPrivateSubnet2SubnetD26CEC08:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.192.0/18
      MapPublicIpOnLaunch: false
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Private
        - Key: aws-cdk:subnet-type
          Value: Private
        - Key: Name
          Value: CdkStack/convert-cfn/PrivateSubnet2
      VpcId:
        Ref: convertcfn1E0C967A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PrivateSubnet2/Subnet
  convertcfnPrivateSubnet2RouteTable9C078D1A:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: CdkStack/convert-cfn/PrivateSubnet2
      VpcId:
        Ref: convertcfn1E0C967A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PrivateSubnet2/RouteTable
  convertcfnPrivateSubnet2RouteTableAssociationDA141600:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: convertcfnPrivateSubnet2RouteTable9C078D1A
      SubnetId:
        Ref: convertcfnPrivateSubnet2SubnetD26CEC08
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PrivateSubnet2/RouteTableAssociation
  convertcfnPrivateSubnet2DefaultRoute42EED26B:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: convertcfnPublicSubnet1NATGateway2E278E89
      RouteTableId:
        Ref: convertcfnPrivateSubnet2RouteTable9C078D1A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/PrivateSubnet2/DefaultRoute
  convertcfnIGWCBCB9568:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CdkStack/convert-cfn
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/IGW
  convertcfnVPCGWBD5A227E:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: convertcfnIGWCBCB9568
      VpcId:
        Ref: convertcfn1E0C967A
    Metadata:
      aws:cdk:path: CdkStack/convert-cfn/VPCGW
  # CDKMetadata:
  #   Type: AWS::CDK::Metadata
  #   Properties:
  #     Analytics: v2:deflate64:H4sIAAAAAAAA/02PzQ6CMBCEn8V7qdr4AoQYw8UQMFxNKWtcflpDtxBDeHeLqHjabyeT2VnB9+LAdxs52ECVddBgwceMpKqZl66gBB/zh2LRTedJxBJXNKgyV2igWVspNY7gIosGVn3VQmuNQklo9M88wzFO5nGWdJIEg3yypMPe4xoca4LO89ewNPlsIfmq9xY0TSwFa1yn3rn/HBld4nx5YtqUwCu77cWeC/91ZRGDzmnCFni6zBeP7UOrEgEAAA==
  #   Metadata:
  #     aws:cdk:path: CdkStack/CDKMetadata/Default
  #   Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```

### Output of `pulumi about`

```text
CLI          
Version      3.104.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v21.2.0'

Current Stack: jkodrofftest/pulumi-cf-convert/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/josh-pulumi-corp
User           josh-pulumi-corp
Organizations  josh-pulumi-corp, pulumi-gitlab-demo2, jkodrofftest, zephyr, getting-started-google-cloud-20240131, pulumi
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.104.0
@types/node     18.19.12

Pulumi locates its logs in /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
