### ISSUE TITLE
cf2pulumi: CloudFormation resource attributes DeletionPolicy / UpdateReplacePolicy expected to be mappings

### ISSUE THREAD

**Issue by PatMyron** [pulumi/pulumi-aws-native#146]
### Steps to reproduce

https://www.pulumi.com/cf2pulumi/
```yaml
Resources:
  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Engine: aurora
      MasterUsername: MasterUsername
      MasterUserPassword: MasterUserPassword
```

Expected: Some [CloudFormation resource attributes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-product-attribute-reference.html) can be strings
Actual: 
[`failed to render template: 'DeletionPolicy' must be a mapping`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html)
[`failed to render template: 'UpdateReplacePolicy' must be a mapping`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html)
https://github.com/pulumi/pulumi-aws-native/blob/886a1d605d958f90c44936a1ce254f92d6fce774/provider/pkg/cf2pulumi/renderer.go#L879-L883

**Comment by PatMyron** [comment]
Similar issue with [`unsupported property 'Condition' in resource 'Resource'`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html):
```yaml
Parameters:
  CreateResource:
    Type: String
Conditions:
  ShouldCreateResource:
    !Equals [true, !Ref CreateResource]
Resources:
  Resource:
    Type: AWS::SNS::Topic
    Condition: ShouldCreateResource
```
