### ISSUE TITLE
pulumi refresh gives errors for certain resources when they are deleted from cloud provider

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi-aws-native#676]
### What happened?

When running `pulumi refresh` and an AWS WAF (Web Application Firewall) association has been created for an API gateway but then the API gateway is deleted manually in the console, I get the following error:

```
  aws-native:wafv2:WebACLAssociation (rest-api:gateway:firewall:association):
    error: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: xxx, ResourceNotFoundException: AWS::WAFv2::WebACLAssociation Handler returned status FAILED: AWS WAF couldn’t perform the operation because your resource doesn’t exist. (Service: Wafv2, Status Code: 400, Request ID: xxx, Extended Request ID: null) (HandlerErrorCode: NotFound, RequestToken: xxx)
```

### Steps to reproduce

Have Pulumi create the following:

1. An AWS WAF Web ACL. 
2. An API gateway with the type "REST Api".
3. A default stage for the API and associate it with the WAF Web ACL.

Then delete the rest API manually.

Then run `pulumi refresh`

### Expected Behavior

Pulumi detects the association as deleted.

### Actual Behavior

It throws an error with a status code 400.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
We can repro by doing a create, import, delete, refresh dance:

We start by creating a `aws-native:logs:LogGroup`.
```yaml
name: proj
runtime: yaml
resources:
  aws:
    type: pulumi:providers:aws-native
    properties:
      region: us-east-1
  group:
    type: aws-native:logs:LogGroup
    options:
      provider: ${aws}

outputs:
  id: ${group.id}
```

We then re-import that resource, giving us a duplicate managed resource:
```yaml
name: proj
runtime: yaml
resources:
  aws:
    type: pulumi:providers:aws-native
    properties:
      region: us-east-1
  group:
    type: aws-native:logs:LogGroup
    options:
      provider: ${aws}
  copy:
    type: aws-native:logs:LogGroup
    options:
      provider: ${aws}
      import: group-47168ca # The value of ${group.id} as a string literal
outputs:
  id: ${group.id}
```

We then remove the copy, deleting the underlying resource:
```yaml
name: proj
runtime: yaml
resources:
  aws:
    type: pulumi:providers:aws-native
    properties:
      region: us-east-1
  group:
    type: aws-native:logs:LogGroup
    options:
      provider: ${aws}

outputs:
  id: ${group.id}
```

Finally, we run `pulumi refresh`. Since the underlying resource has been deleted, `pulumi refresh` should detect the deletion. Instead it errors:

```
❯ pulumi refresh --yes
Please choose a stack, or create a new one: dev
Previewing refresh (dev)

View Live: https://app.pulumi.com/************

     Type                            Name      Plan           Info
     pulumi:pulumi:Stack             proj-dev  running.       error: preview failed
     ├─ pulumi:providers:aws-native  aws                      
 ~   └─ aws-native:logs:LogGroup     group     refreshing.    error: Preview failed: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: *****, ResourceNotFoundException: AWS::Logs::LogGroup Handler returned status FAILED: Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"group-47168ca"}' was not found. (HandlerErrorCode: NotFound, RequestToken: *****

Diagnostics:
  pulumi:pulumi:Stack (proj-dev):
    error: preview failed

  aws-native:logs:LogGroup (group):
    error: Preview failed: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: *****, ResourceNotFoundException: AWS::Logs::LogGroup Handler returned status FAILED: Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"group-47168ca"}' was not found. (HandlerErrorCode: NotFound, RequestToken: *****)

```
